#vpn

#commands
alias ls='exa -a'
alias ll='ls -la --color=auto'
alias gpull='gitf && git pull'
alias vim='nvim'
alias ip='ip -c a'
alias aur-install='makepkg -si'
alias i3config='nvim ~/.config/i3/config'
alias i3status-config='nvim ~/.config/i3status/config'
alias cd2='cd ../..'
alias cd3='cd ../../..'
alias gitf='cd && cd git'
alias gclone='gitf && git clone'
alias dotf='gitf && cd DotFiles'
alias bashrc='cd && vim .bashrc'
alias malias='cd && vim .bash_aliases'
alias i3c='vim ~/.config/i3/config'
alias i3sc='vim ~/.config/i3status/config'
alias spe='cd ~/git/DotFiles/scripts && ./spegni.sh'
alias l='clear'
alias e='exit'

#utility
#alias code='codium'
alias todo='vim ~/TODO.md'
alias batteri3='vim +17 ~/.config/i3status/config'

# alias stabledifusion-start='cd  ~/stablediff/  && ./webui.sh --listen --api'
# alias jacket-torrent-start='cd /home/mark/.local/share/applications/Jackett && ./jackett'
alias cash_ita='LANGUAGE=it_IT LANG=it_IT gnucash'
# alias present='cd ~/Documents/present/'
alias excentio='cd ~/Documents/excentio/'
alias file='nautilus'
alias riordina='/home/mark/git/DotFiles/scripts/riordina.sh'
alias downloadf='cd /home/mark/Downloads'
# alias spotX='bash <(curl -sSL https://spotx-official.github.io/run.sh) -i'
alias diff='diff --color'
alias speedtest-cli='/opt/ookla-speedtest-1.2.0/speedtest'
alias murocarta='cd ~/wallpaper/WallPaper'
alias killtmux='tmux kill-ses -t'
# alias sshPortatile='ssh mark@$portatile'
# alias gnome-extensions-sync="cp -r /home/mark/.local/share/gnome-shell/extensions/* /home/mark/git/gnome-extension && cd /home/mark/git/gnome-extension && supergitpush"
# alias docker_onuse='export docker_inuso='
# alias docker_onuse_console='docker exec -it $docker_inuso /bin/bash'
alias obsidian-sync='cd Documents && cd obsidian_pacchio && git add . && git commit -m "ultime note" && git push'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip'
#alias lspatterns='gitf && cd fabric/patterns && ls' fabbric -l
alias vide='tmuxifier load-session vide'
alias transcrizione='yt --transcript'
alias riassunto='fabric -sp summary'
alias video_content='cd ~/git/DotFiles/scripts && ./video_analisi.sh'
alias backup_dnf_pacchetti='dotf; cd customization; rpm -qa --qf "%{NAME}\n" | grep -vE "^(kernel|glibc|bash|core|systemd|grub2|initramfs|dnf)" > pacchetti.fedora'
# alias auto_backup_dnf='backup_dnf_pacchetti;cd ..; git checkout backup; gadd && gc "super backup" && gpush && gcheck main'
alias music-sync='cd /home/mark/Music/Music/prefe/ && spotdl https://open.spotify.com/playlist/7lzz5VZMbp6d0rSXZURYh6'
alias fileAdmin='nautilus admin:/'
alias ghostty-keybindings='ghostty +list-keybinds --default'
alias kvm_togle='dotf && cd scripts && sudo ./toggle_kvm.sh'
alias java8='sdk default java 8.0.472-zulu'
alias java23='sdk default java 23.0.2-zulu'
alias java21='sdk default java 21.0.9-zulu'

#tmp
# alias beaglebone_c='sudo screen /dev/ttyACM0 115200'
# alias uncensored-ia='ollama run llama2-uncensored:latest'
# alias i2pstart='/home/mark/i2p/i2prouter start'
